### PR TITLE
Add Grey to Color type

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by data-man** [comment]
I'm still waiting for your reply... :grinning:

Q:
> Should we use that?

A:
> Why not?

**Comment by data-man** [comment]
But the most important question is:

>some libraries outputs White (FG/BG Code 37/47) as 97/107.
And **White named as Grey.**
I think it's correct.

Thoughts?

**Comment by joachimschmidt557** [comment]
> I have checked many other implementations in different languages and noticed that some libraries outputs White (FG/BG Code 37/47) as 97/107.
> And White named as Grey.

Ultimately, it's just a naming scheme. According to Wikipedia, 37 is also called `white` and 97 is called `bright white`. I think the name `white` fro 37 is okay.

Regarding the large enums for color names, this can be implemented, but I'd prefer a new file called `color_names.zig` or similar where color names are mapped to the ANSI colors.

**Comment by data-man** [comment]
Ok! :)

> but I'd prefer a new file called color_names.zig or similar where color names are mapped to the ANSI colors.

:+1: 

Now we can create enums in comptime by `@Type`. Just an idea...

**Comment by data-man** [comment]
Are you ok with other color representation?
HSL, HSV, CMYK, ...

**Comment by joachimschmidt557** [comment]
> Are you ok with other color representation?
> HSL, HSV, CMYK, ...

I think stuff like this is out of scope for this library. The basic colors or the 8-bit colors can vary from terminal from terminal and even within one terminal users can have different color themes. Converting RGB (24-bit colors) into HSL, HSV, ... and vice versa should be the job of another library focusing on colors, color spaces, conversions and other color operations.

**Pull request merged**
